branch-defaults:
  master:
    environment: covid19
    group_suffix: null
environment-defaults:
  covid19:
    branch: null
    repository: null
global:
  application_name: covid-19
  branch: null
  default_ec2_keyname: aws-eb3
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
option_settings:
  aws:elasticbeanstalk:environment:process:https:
    Port: '443'
    Protocol: HTTPS
  aws:elbv2:listener:443:
    DefaultProcess: https
    ListenerEnabled: 'true'
    Protocol: HTTPS
