version: '3'

services:

  dash_app:
    container_name: covid_app
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    command: gunicorn -w 1 -b :8050 application.__main__:application